server {
  listen 80;
  listen [::]:80;
  server_name _;

  root /usr/share/nginx/html;
  index presentacion-zero-trust-85-slides.html;

  location = / {
    try_files /presentacion-zero-trust-85-slides.html =404;
  }

  location / {
    try_files $uri $uri/ /presentacion-zero-trust-85-slides.html;
  }
}
